import { defineConfig } from 'vitepress'

// Generated by typedoc-vitepress-theme into docs/reference.
import typedocSidebar from '../reference/typedoc-sidebar.json'

export default defineConfig({
  title: '@uploadcare/cdn-url',
  description:
    'Build and parse Uploadcare CDN URLs: transformations, groups, proxy and conversion paths.',
  // GitHub Pages serves under the repo subpath; Firebase serves at the root.
  base: process.env.DOCS_BASE ?? '/uploadcare-js-api-clients/cdn-url/',
  themeConfig: {
    logo: 'https://ucarecdn.com/edfdf045-34c0-4087-bbdd-e3834921f890/userpiccircletransparent.svg',
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'How-to', link: '/how-to/render-stored-urls' },
      { text: 'API Reference', link: '/reference/' },
      {
        text: 'Uploadcare',
        items: [
          { text: 'uploadcare.com', link: 'https://uploadcare.com' },
          { text: 'Platform docs', link: 'https://uploadcare.com/docs/' },
          {
            text: 'CDN operations reference',
            link: 'https://uploadcare.com/docs/cdn-operations/'
          }
        ]
      }
    ],
    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting started', link: '/guide/getting-started' },
          { text: 'CDN URL anatomy', link: '/guide/url-anatomy' },
          {
            text: 'API styles & tree-shaking',
            link: '/guide/functional-vs-builder'
          },
          { text: 'Dev & production bundles', link: '/guide/bundles' }
        ]
      },
      {
        text: 'How-to',
        items: [
          { text: 'Render stored URLs', link: '/how-to/render-stored-urls' },
          { text: 'Responsive images', link: '/how-to/responsive-images' },
          { text: 'Avatars', link: '/how-to/avatars' },
          {
            text: 'Remote images via proxy',
            link: '/how-to/remote-images-via-proxy'
          },
          { text: 'Groups & archives', link: '/how-to/groups-and-archives' },
          { text: 'Video & documents', link: '/how-to/video-and-documents' },
          { text: 'Validate user input', link: '/how-to/validate-user-input' }
        ]
      },
      { text: 'Best practices', link: '/best-practices' },
      {
        text: 'API Reference',
        link: '/reference/',
        collapsed: true,
        items: typedocSidebar
      }
    ],
    socialLinks: [
      {
        icon: 'github',
        link: 'https://github.com/uploadcare/uploadcare-js-api-clients'
      }
    ],
    search: { provider: 'local' }
  }
})
