name: checks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        working-directory: ./
        run: npm ci
      - name: Run lint
        working-directory: ./
        run: npm run lint
      - name: Run build
        working-directory: ./
        run: npm run build
      - name: Run mock tests
        run: npm run test
      - name: Run integration tests
        run: npm run test:production
        env:
          UC_KEY_FOR_INTEGRATION_TESTS: ${{ secrets.UC_KEY_FOR_INTEGRATION_TESTS }}

